import Head from 'next/head'
import Image from 'next/image'
import ResponsiveAppBar from '../components/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <ResponsiveAppBar/>
      <Head>
        <title>Bem-Vindo a EasyPharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Bem-Vindo a EasyPharma 
        </h1>



      </main>


    </div>
  )
}
